---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: INTR-BZTE-OS
description: Enter AMD/Intel KDE Bazzite based fork with Bloatware Removed

base-image: ghcr.io/ublue-os/bazzite
image-version: stable 

modules:
  - type: files
    files:
      - source: files/system
        destination: /

  - type: rpm-ostree
    install:
      - discord
      - steam
      - mangohud
      - input-remapper
      - gnome-disk-utility
      - fastfetch
    remove:
      - firefox
      - firefox-langpacks
      - libreoffice-core
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-impress
      - libreoffice-writer
      - libreoffice-langpack-en
      - kpat
      - kmahjongg
      - kmines
      - kaddressbook
      - korganizer
      - dragon
      - khelpcenter
      - krdc
      - krfb

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.vinegarhq.Sober
        - com.usebottles.bottles
        - org.videolan.VLC
      remove:
        - org.kde.elisa

  - type: script
    scripts:
      - plymouth-set-default-theme bazzite -R
      - chmod +x /usr/bin/clean-system

  - type: signing
