---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: intr-bzte-os
description: Enter AMD/Intel KDE Bazzite based fork with Bloatware Removed

base-image: ghcr.io/ublue-os/bazzite
image-version: stable 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - mangohud

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.vinegarhq.Sober
        - com.usebottles.bottles
        - org.videolan.VLC
        - com.spotify.Client
        - com.discordapp.Discord

  - type: script
    scripts:
      - plymouth-set-default-theme bazzite -R
      - chmod +x /usr/bin/clean-system
      - systemctl enable battery-limit.service

  - type: signing
