---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: intr-bzte-os
description: Enter AMD build of KDE Bazzite based fork with Bloatware Removed

base-image: ghcr.io/ublue-os/bazzite
image-version: stable 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - mangohud
      - corectrl

  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        - org.vinegarhq.Sober
        - com.usebottles.bottles
        - org.videolan.VLC
        - com.spotify.Client
        - com.discordapp.Discord
        - com.heroicgameslauncher.hgl
        - org.winehq.Wine
        - com.obsproject.Studio
        - org.libretro.RetroArch
        - io.github.benjamimgois.goverlay

  - type: script
    scripts:
      - setup.sh

  - type: signing
